### ISSUE TITLE
Do we need a way to encode PSKs?

### ISSUE THREAD

**Issue by chris-wood** [tlswg/external-psk-design-team#1]
This would, ideally, prohibit one from encoding PSKs as strings, since that tends to lead to less good PSKs. Think PSK = "bananas".

**Comment by BjoernHaase-EH** [comment]
I think that we should be really avoiding this. As mentioned I have a suggestion on how to encode the PSK on my todo list, but will likely only get time starting at the end of the week.
Maybe I could be preparing a 00 version of an I-D for this by monday.

**Comment by chris-wood** [comment]
This is fixed by your I-D -- closing!
