### ISSUE TITLE
Guidance on PSK and identifier structure

### ISSUE THREAD

**Issue by chris-wood** [tlswg/external-psk-design-team#15]
- PSKs: Minimum length? Minimum derivation entropy?
- Identifiers: Can it be any length? Maybe it just needs to be unique to the application?

**Comment by ms-s** [comment]
Does the PSK identity need to have entropy? Can't it be user configurable? EAP identities are generally a NAI (RFC 7542). They look like an email address and are in many cases configured by the user through a GUI.

**Comment by chris-wood** [comment]
Discussed on the call -- I don't think we can say anything meaningful here beyond "it needs to make sense to the application." @ms-s, can you please propose text?

**Comment by chris-wood** [comment]
Let's fold this into #17!
