### ISSUE TITLE
Clarify identity mismatch behavior

### ISSUE THREAD

**Issue by chris-wood** [tlswg/external-psk-design-team#17]
What should servers do if they get an identity which doesn't match a known key? Do they send an alert or try any PSK? (OpenSSL does the latter, it seems.)

   unknown_psk_identity:  Sent by servers when PSK key establishment is
      desired but no acceptable PSK identity is provided by the client.
      Sending this alert is OPTIONAL; servers MAY instead choose to send
      a "decrypt_error" alert to merely indicate an invalid PSK
      identity.

**Comment by ms-s** [comment]
Currently, any identity is accepted as long as a matching PSK is found. For example:
openssl s_server -accept 4433 -psk 1a2b3c4d -nocert -tls1_3 -psk_identity 'test' -trace and
openssl s_client -connect 127.0.0.1:4433 -psk 1a2b3c4d -sess_out sesion -tls1_3 -psk_identity 'wewe' -trace

results in successful connection even though psk_identity at server 'test' does not match psk_identity at client 'wewe'.

Server should either send a fatal "decrypt_error" alert or then "unknown_psk_identity" alert.

**Comment by chris-wood** [comment]
We should also clarify badness that comes from identity collisions. @ms-s, can you please take this?

**Comment by chris-wood** [comment]
Closing in favor of #22.
