### ISSUE TITLE
PSK privacy implications

### ISSUE THREAD

**Issue by ms-s** [tlswg/external-psk-design-team#36]
Carrick Bartle in her review writes:
>  Applications should take precautions when using external PSKs to mitigate these risks.
What sort of precautions should they take?

Do we want to make any recommendations. Jim Schaad provided some recommendation on the mailing list:
https://mailarchive.ietf.org/arch/msg/tls/CJ0YrVI9Gy7LFE032xytwrz7mmo/ 

[JLS] There are going to be three different cases for external PSK identities: The identity if factory provisioned and carried in a file to the server,  the identity is factory provisioned and read by the user from the device, and it is hand chosen.  The first two cases can definitely be randomized.  I don’t know that having a minimum length makes any difference.  This is not exactly a cryptographic property.  Another thing that might be done would be analogous to the PSK importer document and apply a one way hash from the typed in value to the value that is sent over the wire so on the wire it is just a random set of bytes.

**Comment by chris-wood** [comment]
nit: s/his/her :-)

**Comment by cbartle891** [comment]
Isn't there a fourth case JLS didn't mention, namely some other out-of-band provisioning over a secure connection? In that case, a new PSK could be provisioned after each use. (This might seem silly, but I've seen two separate use-cases for this.)

Alternatively, in any of those cases, is it feasible to do some sort of ratcheting? (This is sort of expanding on the last sentence in JLS's paragraph.)

**Comment by chris-wood** [comment]
Hmm, @cbartle891, there is. I'm wary about writing down any sort of recommendation here, though, as they would probably require analysis. (In contrast to the recommendations about PSK length, for which we understand the requirements quite well, I don't think we have a good way to reason about techniques to deal with external PSK privacy... yet.)

**Comment by cbartle891** [comment]
In that case, I'm in favor of deleting this line: "Applications should take precautions when using external PSKs to mitigate these risks." Mentioning precautions we don't describe is less helpful than not mentioning them at all (since it's confusing).

Even better though would be to state that such precautions are an open problem that require analysis.

**Comment by chris-wood** [comment]
Yep, that seems reasonable to me!

**Comment by jimsch** [comment]
@cbartle891 - At this point I would implement the - lets roll over the PSK on each use into the case of issuing tokens and just void the PSK (and token) on the first usage.

**Comment by jimsch** [comment]
@chris-wood What type of analysis are you looking for on this?  It hardly needs to have a cryptographic analysis since this is not a cryptographic property.   Are you looking for some analysis that the input and output cannot be correlated?

**Comment by chris-wood** [comment]
> @chris-wood What type of analysis are you looking for on this? It hardly needs to have a cryptographic analysis since this is not a cryptographic property. Are you looking for some analysis that the input and output cannot be correlated?

Minimally, yes.

**Comment by jimsch** [comment]
While it may be odd - you could ask the PSK importer document to do this and just note the privacy problem here.

**Comment by chris-wood** [comment]
@jimsch would you mind proposing text (preferably for this document)?

**Comment by cbartle891** [comment]
@jimsch What sort of tokens are you referring to?

**Comment by jimsch** [comment]
@cbartle891 In this case the token should be ticket.  I have token on the brain because that is what we use for a similar idea in ACE.

**Comment by chris-wood** [comment]
@ms-s @cbartle891, do you think this issue is resolved?

**Comment by cbartle891** [comment]
Yep!

**Comment by chris-wood** [comment]
Excellent -- closing as is!
