### ISSUE TITLE
Why use both certificates and a PSK on the same connection?

### ISSUE THREAD

**Issue by cbartle891** [tlswg/external-psk-design-team#44]
(This question is copied from my email.)

The draft states: "To perform rare system specific operations that require a higher security level, the central server can request resource-intensive client authentication with the usage of a certificate after successfully establishing the connection with a PSK."

If you're going to authenticate with a cert, why bother preceding that 
with an authentication with a PSK?

**Comment by chris-wood** [comment]
@ms-s can you please take this?

**Comment by ms-s** [comment]
#45  and this refer to the same use-case and can be merged.

This use-case is described in the publication by Akhmetzyanova et al. https://eprint.iacr.org/2019/421.pdf. See section 4. In the scenario described by the authors, resource-constrained IoT devices are TLS clients. The PSK is used for authenticating the central server and client membership of the system. Only for rare device-specific operations requiring a higher-security level (such as device firmware update), the server can request resource-intensive client authentication with certificates after successfully establishing the connection with PSK. This deployment may seem somewhat artificial but it was necessary 
in the paper to explain the possible attack scenarios.

Also answered on the mailing list here: https://mailarchive.ietf.org/arch/msg/tls/jdTQu9O-3WS2efav_ciI1uKf9mQ/

**Comment by cbartle891** [comment]
That rephrases the content in the draft; I guess what I'm asking for is a brief explanation as to why authenticating the client with a certificate is necessary to circumvent those attack scenarios.
