### ISSUE TITLE
Further detail needed on distributing pair-wise keys

### ISSUE THREAD

**Issue by cbartle891** [tlswg/external-psk-design-team#47]
(Also adding this question from the email.)

The draft states: "PSK provisioning systems are often constrained in application-specific ways. For example, although one goal of provisioning is to ensure that each pair of nodes has a unique key pair, some systems do not want to distribute pair-wise shared keys to achieve this."

Why wouldn't a system want to distribute pair-wise keys? What application-specific constraint would warrant that? (I'm imagining, for instance, that maybe that would overload the network or something, but the reason should probably be explained rather than left to the imagination.)

**Comment by chris-wood** [comment]
@ms-s can you please take this?

**Comment by ms-s** [comment]
This text is based on the input from Björn Haase. Essentially, he indicated that some industrial control deployments do not want to have O(n^2) keys for a system with n nodes, but they do want to minimize sharing. I am fine with changing it to "might not want to" or removing this constraint completely. 

Also answered on the mailing list here: https://mailarchive.ietf.org/arch/msg/tls/jdTQu9O-3WS2efav_ciI1uKf9mQ/

**Comment by cbartle891** [comment]
Ah, that seems like an important point to mention. It makes sense that provisioning O(n^2) keys would be overburdensome on a system, but if it doesn't, there are security trade-offs, right?

**Comment by chris-wood** [comment]
> Ah, that seems like an important point to mention. It makes sense that provisioning O(n^2) keys would be overburdensome on a system, but if it doesn't, there are security trade-offs, right?

Yep. @cbartle891: what sort of change are you looking for here?

**Comment by cbartle891** [comment]
@jhoyla's change works for me.
