### ISSUE TITLE
The "ordinary process" of incorporating external PSKs

### ISSUE THREAD

**Issue by cbartle891** [tlswg/external-psk-design-team#50]
(This question is copied from my email with greater context from the draft.)

Section 7.1 is the following:

"Each PSK SHOULD be derived from at least 128 bits of entropy, MUST be at least 128 bits long, and SHOULD be combined with a DH exchange for forward secrecy. As discussed in Section 4, low entropy PSKs, i.e., those derived from less than 128 bits of entropy, are subject to attack and SHOULD be avoided. If only low-entropy keys are available, then key establishment mechanisms such as Password Authenticated Key Exchange (PAKE) that mitigate the risk of offline dictionary attacks SHOULD be employed. Note that these mechanisms do not necessarily follow the same architecture as the ordinary process for incorporating EPSKs described in this draft."

Where was the ordinary process for incorporating EPSKs described? Is "incorporating" a PSK the same as "provisioning" one? If so, several ways were described. What's the problem with these mechanisms (e.g. PAKE) having a different architecture from these ordinary processes? Are they not compatible?

**Comment by jhoyla** [comment]
Perhaps this refers to the process in I-D.ietf-tls-external-psk-importer, which takes a provisioned PSK and performs a transformation on it to ensure that it is unique? That can then be incorporated into the key schedule. 
This is different from the PAKE process, which doesn't pass through the ePSK importer mechanism. 
Not sure if that was the original intention, but if so we should write clarifying text.
