### ISSUE TITLE
PSK Security Properties Incomplete

### ISSUE THREAD

**Issue by jhoyla** [tlswg/external-psk-design-team#54]
The sentence "TLS 1.3 tries to maintain the following seven security properties:" leaves out the eighth property, "Protection of Endpoint Identities". 
The reason it was left out is (presumably) because RFC explicitly calls out protection of certificates, but in Section 5 we discuss the privacy properties of PSKs, so it seems appropriate to mention it here, even if to say that it doesn't apply directly.
See #36.

**Comment by jhoyla** [comment]
We also mention "Protection of Endpoint Identities" in Section 3.1 which becomes something of a non-sequitur.

**Comment by chris-wood** [comment]
I don't see this sentence in the document, so I'm considering this overcome by events! Please re-open (and send a PR) if you think it's not addressed.
