### ISSUE TITLE
TLS 1.3 vs 1.2 API

### ISSUE THREAD

**Issue by ms-s** [tlswg/external-psk-design-team#61]
The draft says “OpenSSL and BoringSSL: Applications specify support for external PSKs via distinct ciphersuites.”

John wrote: I assume this is not the case for TLS 1.3 as the cipher suites in TLS 1.3 are independent of the authentication.

**Comment by ms-s** [comment]
I guess it would help to clarify. In my opinion, we should only look at APIs of TLS 1.3.

**Comment by chris-wood** [comment]
I fixed this directly on main.
