### ISSUE TITLE
Adding security weaknesses of two party PSK

### ISSUE THREAD

**Issue by ms-s** [tlswg/external-psk-design-team#63]
John wrote: There also several weaknesses/limitation that are hinted at in RFC 8446 which apply for two-party PSK authenticated connections. As this is a guidance document for all uses of external PSK, I think this document should bring up and expand upon:

-	Key Compromise Impersonation (KCI) resistance 
-	Protection of endpoint identities  
-	Forward secret with respect to long-term keys (psk_ke only) 

An additional security property given by signature authentication but not psk authentication is non-repudiation. As stated by Wikipedia “By this property, an entity that has signed some information cannot at a later time deny having signed it.”

**Comment by ms-s** [comment]
This is a fair comment and I don't see any reason not to add these

**Comment by chris-wood** [comment]
@ms-s, can you please send a PR?

**Comment by chris-wood** [comment]
Closing as resolved (by #65).
