### ISSUE TITLE
Early data considerations

### ISSUE THREAD

**Issue by chris-wood** [tlswg/external-psk-design-team#76]
From @martinthomson:

> A specific concern is the somewhat offhand way that early data is treated.  The only mention is in a throwaway: "primarily for the purposes of supporting TLS connections with early data" buried in a bullet in Section 6.  This is a pretty big topic and having absolutely no mention seems odd.  I do think that it needs some treatment in the document.  When early data is used with an external PSK, the only additional source of entropy that provides key diversity is the client's random value, which puts a lot of weight on that value containing sufficient entropy.  In this case, even if the PSK is good enough, the entropy in the random is significant as it is what ensures traffic key diversity if the PSK is reused.  Reusing a PSK for early data also likely leads to poor anti-replay performance if the random is not good enough.

This is a great point. We can add some language which describes considerations for external PSK reuse with early data.

**Comment by russhousley** [comment]
Martin:

I think we should add:

When early data is used with an external PSK, the random value in the ClientHello
is the only source of entropy that makes the keying material for the early data
associated with one session different from the keying material for the early data
associated win another session.  As a result, when the external PSK is used more
than one time, the random number source on the client has a significant role in
the protection of the early data.

However, this does not address the last point.  Early data always has replay concerns.  This was discussed at length during the development of RFC 8446.  This is the reason that RFC 8446 says that clients "MUST only send early data which they deem safe to be replayed."  With that warning in RFC 8446, what more needs to be said here?

**Comment by martinthomson** [comment]
Not sure what you mean regarding the last point, but this is a good contribution.

How about (copy editing only):

> When early data is used with an external PSK, the random value in the ClientHello is the only source of entropy that contributes to key diversity between sessions. As a result, when an external PSK is used more than one time, the random number source on the client has a significant role in the protection of the early data.

**Comment by chris-wood** [comment]
That reads pretty well to me. Thanks, @martinthomson!

**Comment by kaduk** [comment]
MT's text also looks good to me.

I'm not sure I understand the (as-yet-unaddressed) point about anti-replay performance, though.
I mean, I can parse it -- it's a claim that (some? all?) anti-replay implementations will incur more runtime cost than in scenarios where the PSK is reused and the random data is "not good enough".  But how would that come to happen?  Are we imagining an implementation that uses a hash table and inputs the client random as the hash input, and "not good enough" randomness would cause unbalanced hashing?  Or is the nature of the concern on a totally different axis?

**Comment by martinthomson** [comment]
Yeah, I think that we can let that point lie.  The NSS anti-replay implementation is somewhat vulnerable to hash stacking, but the effect is that early data is accepted less often, it's not that server CPU cycles are wasted.
